email: kai.korpimies@helsinki.fi
description: >- # this means to ignore newlines until "baseurl:"
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://ohjelmistotekniikka-hy.github.io' # the base hostname & protocol for your site, e.g. http://example.com
github_username: kkorpim
repo_url: 'https://github.com/ohjelmistotekniikka-hy/ohjelmistotekniikka-hy.github.io'
repo_branch: 'master'

# Kurssikertaan liittyvät muuttujat:
title: "Aineopintojen harjoitustyö: ohjelmistotekniikka, syksy 2023"

# timetable (in the format day dd.mm time)
fi_wk1dl: "tiistai 7.11. klo 23:59"
fi_wk2dl: "tiistai 14.11. klo 23:59"
fi_wk3dl: "tiistai 21.11. klo 23:59"
fi_wk4dl: "tiistai 28.11. klo 23:59"
fi_wk5dl: "tiistai 5.12. klo 23:59"
fi_wk6dl: "tiistai 12.12. klo 23:59"
fi_finaldl: "perjantai 22.12. klo 23:59"
fi_code_review_start_date: "torstai 7.12. klo 14"

en_wk1dl: "Tuesday 7.11. at 23:59"
en_wk2dl: "Tuesday 14.11. at 23:59"
en_wk3dl: "Tuesday 21.11. at 23:59"
en_wk4dl: "Tuesday 28.11. at 23:59"
en_wk5dl: "Tuesday 5.12. at 23:59"
en_wk6dl: "Tuesday 12.12. at 23:59"
en_finaldl: "Friday 22.12. at 23:59"
en_code_review_start_date: "Thursday 7.12. at 14:00"

# ohjausajat
# - Maanantaisin klo 14-16  [zoom](https://helsinki.zoom.us/j/68570587158?pwd=TFhwUXBucExZeVNJZnRydE8yWkNFdz09)
# - Tiistaisin klo 14-16  [zoom](https://helsinki.zoom.us/j/65324719978) (alkaen 23.3.)
# - Torstaisin klo 13-15  [zoom]()
fi_times:
  - time: "Maanantaisin klo 10 - 12 kampuksella BK107-luokassa"
  - time: "Tiistaisin klo 10 - 12 kampuksella BK107-luokassa"
  - time: "Keskiviikkoisin klo 10 - 12 kampuksella BK107-luokassa"
  - time: "Keskiviikkoisin klo 14 - 16 kampuksella BK107-luokassa"
  - time: "Torstaisin klo 14 - 16 kampuksella BK107-luokassa"

en_times:
  - time: "Mondays 10 - 12 on campus in the BK107 class"
  - time: "Tuesdays 10 - 12 on campus in the BK107 class"
  - time: "Wednesdays 10 - 12 on campus in the BK107 class"
  - time: "Wednesdays 14 - 16 on campus in the BK107 class"
  - time: "Thursdays 14 - 16 on campus in the BK107 class"

fi_lecture_time: 'keskiviikkona 1.11. klo 10.15 - 11.45'
en_lecture_time: 'Wednesday 1.11. at 10.15 - 11.45'
lecture_link: 'https://github.com/ohjelmistotekniikka-hy/ohjelmistotekniikka-hy.github.io/tree/master/luennot/2023-kevat'
lecture_slides_link: 'https://ohjelmistotekniikka-hy.github.io/luennot/2023-syksy/aloitusluento.pdf'
lecture_recording_link: 'https://moodle.helsinki.fi/mod/lti/view.php?id=3384745'

# seuraava kurssikerta muodossa syksyllä/keväällä [vuosi].
# esimerkki syksyllä 2021
# käytetään muun muassa "ei voi jatkaa seuraavalla kurssilla (syksyllä 2021)"
fi_next_course: 'keväällä 2024'
en_next_course: 'spring 2024'

labtool_link: 'https://study.cs.helsinki.fi/labtool/courses/TKT20018.2023.S.K.1'

# referenssi-sovellusten linkit
python_reference_app_url: 'https://github.com/ohjelmistotekniikka-hy/python-todo-app'
java_reference_app_url: 'https://github.com/mluukkai/OtmTodoApp'

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
